import { Baloo_2, Comfortaa } from "next/font/google";

export const baloo = Baloo_2({
    subsets: ["latin"],
    variable: "--font-baloo",
    weight: ["400", "500", "600", "700", "800"],
    style: ["normal"],
    display: "swap",
    fallback: []
})

export const comfortaa = Comfortaa({
    subsets: ["cyrillic"],
    weight: ["300", "400", "500", "600", "700"],
    variable: "--font-comfortaa",
    display: "swap",
    fallback: []
})

const THEME_COLOR = "#2d2a2e"

export const _metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export const _viewport = {
    themeColor: THEME_COLOR
}