import { Balsamiq_Sans, Comfortaa } from "next/font/google"
import localFont from "next/font/local"

// Основной шрифт
export const comfortaa = Comfortaa({
    subsets: ['latin', 'cyrillic'],
    weight: ["300", "400", "500", "600", "700"],
    variable: "--font-comfortaa",
    display: "swap"
})

// Второстепенный шрифт для заголовков
export const balsamiqSans = Balsamiq_Sans({
    subsets: ['latin', 'cyrillic'],
    variable: "--font-balsamiq",
    weight: ["400", "700"],
    display: "swap"
})

// Шрифт для личных записей
export const asinastra = localFont({
    src: "./styles/fonts/Asinastra.otf",
    variable: "--font-asinastra",
    display: "swap",
})

const THEME_COLOR = "#2d2a2e"

export const _metadata = {
    title: "MaSStiK.dev",
    description: "Generated by create next app",
}

export const _viewport = {
    themeColor: THEME_COLOR
}